apiVersion: v1
kind: Pod
metadata:
  name: ultra-secure-app
spec:
  serviceAccountName: myapp-service-account
  automountServiceAccountToken: false
  
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    appArmorProfile:
      type: RuntimeDefault
    seccompProfile:
      type: RuntimeDefault
    seLinuxOptions:
      level: "s0:c123,c456"
  
  imagePullSecrets:
  - name: private-registry-secret
  
  containers:
  - name: app
    image: private-registry.company.com/myapp:v1.2.3
    imagePullPolicy: Always

    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
        add:
        - NET_BIND_SERVICE
    env:
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: app-secrets
          key: database-password
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: app-secrets
          key: api-key
    envFrom:
    - configMapRef:
        name: app-config
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
        ephemeral-storage: "1Gi"
      limits:
        memory: "512Mi"
        cpu: "500m"
        ephemeral-storage: "2Gi"
    livenessProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 10
    
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
    volumeMounts:
    - name: tmp-volume
      mountPath: /tmp
    - name: app-secrets
      mountPath: /etc/secrets
      readOnly: true
    ports:
    - containerPort: 8080
      protocol: TCP
  volumes:
  - name: tmp-volume
    emptyDir: {}
  - name: app-secrets
    secret:
      secretName: app-secrets
      defaultMode: 0400

  restartPolicy: Always
  dnsPolicy: ClusterFirst

---
# Supporting resources

apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp-service-account
automountServiceAccountToken: false

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  database-password: bXktc3VwZXItc2VjcmV0LXBhc3N3b3Jk
  api-key: c2stMTIzNDU2Nzg5MGFiY2RlZg==

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  LOG_LEVEL: "info"
  ENVIRONMENT: "production"
  MAX_CONNECTIONS: "100"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: myapp-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: myapp-rolebinding
subjects:
- kind: ServiceAccount
  name: myapp-service-account
roleRef:
  kind: Role
  name: myapp-role
  apiGroup: rbac.authorization.k8s.io