apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  labels:
    app: wordpress
stringData:
  WORDPRESS_DB_PASSWORD: SecureWPPassword456!
  WORDPRESS_AUTH_KEY: your-auth-key-here
  WORDPRESS_SECURE_AUTH_KEY: your-secure-auth-key-here
  WORDPRESS_LOGGED_IN_KEY: your-logged-in-key-here
  WORDPRESS_NONCE_KEY: your-nonce-key-here
type: Opaque
