apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      containers:
        - name: strapi
          image: my-strapi-blog:latest # can be replaced with wofet86855/strapi 
          imagePullPolicy: Never
          ports:
            - containerPort: 1337